import {
  getAgent,
  getAllele,
  getChildren,
  getEdgesFor,
  getGene,
  getGenome,
  getMutation,
  getMutationsForGenome,
  getSiblings,
} from '@/lib/registry';
import { accessionHref } from '@/lib/schema/accession';
import type { Attestation } from '@/lib/schema/common';
import type { Genome } from '@/lib/schema/genome';
import { EDGE_TYPE_META, type EdgeType } from '@/lib/schema/vocabulary';

/**
 * Provenance as the existing standards would draw it.
 *
 * The registry's genetic vocabulary is a reading of this graph, not a
 * replacement for it. A genome is a PROV entity, a mutation is an activity, an
 * agent is an agent, and the attestations are in-toto statements bound to
 * digests. This module reconstructs that reading from the fixtures rather than
 * inventing a second evidence universe.
 *
 * Signatures are not re-checked in the browser. `verified` means the seed data
 * says the signature checked at ingest.
 */

export type ProvKind = 'entity' | 'activity' | 'agent';

export type ProvRelation =
  | 'wasDerivedFrom'
  | 'wasGeneratedBy'
  | 'used'
  | 'wasAssociatedWith'
  | 'wasAttributedTo'
  | 'actedOnBehalfOf';

export type ProvNode = {
  id: string;
  kind: ProvKind;
  label: string;
  href: string | null;
  detail: string;
};

export type ProvTriple = {
  subject: string;
  relation: ProvRelation;
  object: string;
  gloss: string;
};

export type InTotoStatement = {
  type: Attestation['type'];
  typeLabel: string;
  predicateType: string;
  subjectName: string;
  subjectDigest: string;
  issuer: string;
  issuedAt: string;
  verified: boolean;
  /** Reconstructed Statement v1. The original predicate body is not in the fixtures. */
  statement: Record<string, unknown>;
};

export type SlsaView = {
  level: 0 | 1 | 2;
  label: string;
  basis: string;
  next: string;
};

export type PedigreeLink = {
  role: 'ancestor' | 'descendant' | 'variant' | 'commit' | 'patch';
  name: string;
  accession: string;
  href: string | null;
  detail: string;
};

export type ProvenanceRecord = {
  subject: { accession: string; name: string; kind: 'genome' | 'mutation' };
  slsa: SlsaView;
  statements: InTotoStatement[];
  pedigree: PedigreeLink[];
  nodes: ProvNode[];
  triples: ProvTriple[];
  counts: {
    entities: number;
    activities: number;
    agents: number;
    triples: number;
    verified: number;
    unverified: number;
  };
};

const ATTESTATION_LABEL: Record<Attestation['type'], string> = {
  'slsa-provenance': 'SLSA provenance',
  'in-toto-test-result': 'in-toto test result',
  'cyclonedx-pedigree': 'CycloneDX pedigree',
  'spdx-document': 'SPDX document',
  'github-artifact-attestation': 'GitHub artifact attestation',
};

const RELATION_GLOSS: Record<ProvRelation, string> = {
  wasDerivedFrom: 'derived from',
  wasGeneratedBy: 'generated by',
  used: 'used',
  wasAssociatedWith: 'associated with',
  wasAttributedTo: 'attributed to',
  actedOnBehalfOf: 'acted on behalf of',
};

function node(id: string, kind: ProvKind, label: string, detail: string): ProvNode {
  return { id, kind, label, href: accessionHref(id), detail };
}

function triple(subject: string, relation: ProvRelation, object: string, gloss: string): ProvTriple {
  return { subject, relation, object, gloss };
}

function digestHex(digest: string): string {
  return digest.startsWith('sha256:') ? digest.slice(7) : digest;
}

function slsaFrom(attestations: Attestation[]): SlsaView {
  const slsa = attestations.filter(
    (entry) =>
      (entry.type === 'slsa-provenance' || entry.type === 'github-artifact-attestation') &&
      entry.predicateType.includes('slsa.dev/provenance'),
  );
  const verified = slsa.filter((entry) => entry.verified);
  const hosted = verified.some(
    (entry) =>
      entry.type === 'github-artifact-attestation' || entry.issuer.includes('.github/workflows'),
  );

  if (hosted) {
    return {
      level: 2,
      label: 'Build L2',
      basis:
        'A hosted build service issued verified SLSA provenance (a workflow file or a GitHub artifact attestation). That is the shape of Build L2: the provenance is generated by the builder, not by the developer laptop.',
      next: 'Build L3 would require a hardened, isolated build platform and two-party review. The fixtures do not attest that, and this page will not claim it.',
    };
  }

  if (verified.length > 0) {
    return {
      level: 1,
      label: 'Build L1',
      basis:
        'Verified SLSA provenance is on record, but the issuer is not a hosted build workflow. That documents how the artifact was produced without proving a hosted builder produced the provenance.',
      next: 'Build L2 needs the provenance to be generated by the build service itself — a workflow file or a GitHub artifact attestation.',
    };
  }

  if (slsa.length > 0) {
    return {
      level: 0,
      label: 'Attested, unverified',
      basis:
        'SLSA provenance is attached but marked unverified in the seed data. An unverified attestation is a claim, not a check.',
      next: 'Verification at ingest would raise this to Build L1 or L2, depending on who issued it.',
    };
  }

  return {
    level: 0,
    label: 'Not attested',
    basis:
      'No SLSA provenance is on record. Inventory documents (CycloneDX, SPDX) describe what is in the tree; they do not describe how it was built.',
    next: 'A slsa-provenance or github-artifact-attestation attestation, verified at ingest, is the first rung.',
  };
}

function statementFrom(attestation: Attestation, subjectName: string): InTotoStatement {
  const hex = digestHex(attestation.subjectDigest);

  return {
    type: attestation.type,
    typeLabel: ATTESTATION_LABEL[attestation.type],
    predicateType: attestation.predicateType,
    subjectName,
    subjectDigest: attestation.subjectDigest,
    issuer: attestation.issuer,
    issuedAt: attestation.issuedAt,
    verified: attestation.verified,
    statement: {
      _type: 'https://in-toto.io/Statement/v1',
      subject: [{ name: subjectName, digest: { sha256: hex } }],
      predicateType: attestation.predicateType,
      predicate: {
        issuer: attestation.issuer,
        issuedAt: attestation.issuedAt,
        reconstructed: true,
        note: 'Reconstructed from the registry attestation record. The original predicate body is not stored in the seed fixtures.',
      },
    },
  };
}

function finalise(
  subject: ProvenanceRecord['subject'],
  attestations: Attestation[],
  nodes: ProvNode[],
  triples: ProvTriple[],
  pedigree: PedigreeLink[],
  statementSubject: string,
): ProvenanceRecord {
  const seen = new Map<string, ProvNode>();
  for (const entry of nodes) {
    if (!seen.has(entry.id)) seen.set(entry.id, entry);
  }
  const unique = [...seen.values()];

  const statements = attestations.map((entry) => statementFrom(entry, statementSubject));

  return {
    subject,
    slsa: slsaFrom(attestations),
    statements,
    pedigree,
    nodes: unique,
    triples,
    counts: {
      entities: unique.filter((entry) => entry.kind === 'entity').length,
      activities: unique.filter((entry) => entry.kind === 'activity').length,
      agents: unique.filter((entry) => entry.kind === 'agent').length,
      triples: triples.length,
      verified: statements.filter((entry) => entry.verified).length,
      unverified: statements.filter((entry) => !entry.verified).length,
    },
  };
}

export function getProvenanceForGenome(id: string): ProvenanceRecord | null {
  const genome = getGenome(id);
  if (!genome) return null;

  const nodes: ProvNode[] = [
    node(
      genome.id,
      'entity',
      genome.name,
      `Generation ${genome.generation} · ${genome.source.commit.slice(0, 10)}`,
    ),
  ];
  const triples: ProvTriple[] = [];
  const pedigree: PedigreeLink[] = [];

  for (const parent of genome.parents) {
    const parentGenome = getGenome(parent.genome);
    const name = parentGenome?.name ?? parent.genome;
    nodes.push(
      node(
        parent.genome,
        'entity',
        name,
        `${parent.relationship} · ${Math.round(parent.contribution * 100)}%`,
      ),
    );
    triples.push(
      triple(
        genome.id,
        'wasDerivedFrom',
        parent.genome,
        `${genome.name} ${parent.relationship === 'hybrid' ? 'recombined from' : 'descends from'} ${name}`,
      ),
    );
    pedigree.push({
      role: 'ancestor',
      name,
      accession: parent.genome,
      href: accessionHref(parent.genome),
      detail: `${parent.relationship}, ${Math.round(parent.contribution * 100)}% · commit:${parent.bornFromCommit.slice(0, 10)}`,
    });
  }

  for (const child of getChildren(genome.id)) {
    nodes.push(node(child.id, 'entity', child.name, `Generation ${child.generation}`));
    triples.push(
      triple(child.id, 'wasDerivedFrom', genome.id, `${child.name} descends from ${genome.name}`),
    );
    pedigree.push({
      role: 'descendant',
      name: child.name,
      accession: child.id,
      href: accessionHref(child.id),
      detail: `Generation ${child.generation}`,
    });
  }

  for (const sibling of getSiblings(genome.id)) {
    pedigree.push({
      role: 'variant',
      name: sibling.name,
      accession: sibling.id,
      href: accessionHref(sibling.id),
      detail: `Generation ${sibling.generation} · shares a parent`,
    });
  }

  pedigree.push({
    role: 'commit',
    name: `commit:${genome.source.commit.slice(0, 10)}`,
    accession: genome.source.commit,
    href: githubCommitUrl(genome),
    detail: `${genome.source.repository} @ ${genome.source.defaultBranch}`,
  });

  for (const agentId of genome.agents) {
    const agent = getAgent(agentId);
    const name = agent?.displayName ?? agentId;
    nodes.push(node(agentId, 'agent', name, agent?.identity.provider ?? 'agent'));
    triples.push(
      triple(genome.id, 'wasAttributedTo', agentId, `${genome.name} is attributed to ${name}`),
    );
  }

  const mutations = getMutationsForGenome(genome.id);
  for (const mutation of mutations) {
    const gene = getGene(mutation.gene);
    nodes.push(
      node(
        mutation.id,
        'activity',
        mutation.shortId,
        `${mutation.title} · ${mutation.state.replaceAll('-', ' ')}`,
      ),
    );

    const agent = getAgent(mutation.proposedBy);
    if (agent) {
      nodes.push(node(agent.id, 'agent', agent.displayName, agent.identity.provider));
      triples.push(
        triple(
          mutation.id,
          'wasAssociatedWith',
          agent.id,
          `${mutation.shortId} was proposed by ${agent.displayName}`,
        ),
      );
    }

    if (mutation.originGenome === genome.id) {
      triples.push(
        triple(
          mutation.id,
          'used',
          genome.id,
          `${mutation.shortId} was authored against ${genome.name}`,
        ),
      );
      pedigree.push({
        role: 'patch',
        name: `${mutation.shortId} ${mutation.title}`,
        accession: mutation.id,
        href: accessionHref(mutation.id),
        detail: `Originated here · ${gene?.name ?? mutation.gene}`,
      });
    }

    if (mutation.adoptedBy.includes(genome.id)) {
      triples.push(
        triple(
          genome.id,
          'wasDerivedFrom',
          mutation.id,
          `${genome.name} adopted ${mutation.shortId}`,
        ),
      );
    }
  }

  for (const edge of getEdgesFor(genome.id)) {
    const meta = EDGE_TYPE_META[edge.type as EdgeType];
    if (!meta) continue;
    if (edge.from !== genome.id && edge.to !== genome.id) continue;
    /* Descent and adoption already appear as wasDerivedFrom; keep the
       sideways and upstream edges, which PROV would otherwise lose. */
    if (edge.type === 'PROPOSED_TO' && edge.mutation) {
      triples.push(
        triple(
          edge.mutation,
          'used',
          edge.to,
          `${edge.mutation} was offered to ${getGenome(edge.to)?.name ?? edge.to}`,
        ),
      );
    }
    if (edge.type === 'TRANSFERRED_FROM' && edge.gene) {
      const gene = getGene(edge.gene);
      triples.push(
        triple(
          genome.id,
          'wasDerivedFrom',
          edge.to,
          `${gene?.name ?? edge.gene} transferred from ${getGenome(edge.to)?.name ?? edge.to}`,
        ),
      );
    }
  }

  return finalise(
    { accession: genome.id, name: genome.name, kind: 'genome' },
    genome.attestations,
    nodes,
    triples,
    pedigree,
    genome.id,
  );
}

export function getProvenanceForMutation(id: string): ProvenanceRecord | null {
  const mutation = getMutation(id);
  if (!mutation) return null;

  const origin = getGenome(mutation.originGenome);
  const gene = getGene(mutation.gene);
  const from = getAllele(mutation.fromAllele);
  const to = getAllele(mutation.toAllele);
  const agent = getAgent(mutation.proposedBy);

  const nodes: ProvNode[] = [
    node(mutation.id, 'activity', mutation.shortId, mutation.title),
  ];
  const triples: ProvTriple[] = [];
  const pedigree: PedigreeLink[] = [];

  if (from) {
    nodes.push(
      node(from.allele.id, 'entity', `${from.gene.name} ${from.allele.version}`, 'reference allele'),
    );
    triples.push(
      triple(mutation.id, 'used', from.allele.id, `${mutation.shortId} used ${from.allele.version}`),
    );
  }

  if (to) {
    nodes.push(
      node(to.allele.id, 'entity', `${to.gene.name} ${to.allele.version}`, 'alternate allele'),
    );
    triples.push(
      triple(
        to.allele.id,
        'wasGeneratedBy',
        mutation.id,
        `${to.allele.version} was generated by ${mutation.shortId}`,
      ),
    );
    if (from) {
      triples.push(
        triple(
          to.allele.id,
          'wasDerivedFrom',
          from.allele.id,
          `${to.allele.version} derived from ${from.allele.version}`,
        ),
      );
    }
  }

  if (origin) {
    nodes.push(node(origin.id, 'entity', origin.name, `Generation ${origin.generation}`));
    triples.push(
      triple(mutation.id, 'used', origin.id, `${mutation.shortId} was authored in ${origin.name}`),
    );
    pedigree.push({
      role: 'ancestor',
      name: origin.name,
      accession: origin.id,
      href: accessionHref(origin.id),
      detail: `Origin · generation ${origin.generation}`,
    });
  }

  if (agent) {
    nodes.push(node(agent.id, 'agent', agent.displayName, agent.identity.provider));
    triples.push(
      triple(
        mutation.id,
        'wasAssociatedWith',
        agent.id,
        `${mutation.shortId} was proposed by ${agent.displayName}`,
      ),
    );
  }

  if (gene) {
    pedigree.push({
      role: 'variant',
      name: gene.name,
      accession: gene.id,
      href: accessionHref(gene.id),
      detail: `${from?.allele.version ?? mutation.fromAllele} → ${to?.allele.version ?? mutation.toAllele}`,
    });
  }

  pedigree.push({
    role: 'commit',
    name: `commit:${mutation.change.commit.slice(0, 10)}`,
    accession: mutation.change.commit,
    href: origin ? githubCommitUrl(origin, mutation.change.commit) : null,
    detail: `ref ${mutation.change.refDigest} → alt ${mutation.change.altDigest}`,
  });

  pedigree.push({
    role: 'patch',
    name: mutation.title,
    accession: mutation.id,
    href: accessionHref(mutation.id),
    detail: `${mutation.change.symbolsChanged} symbols · ${mutation.change.testSuitesTouched} test suites`,
  });

  for (const genomeId of mutation.adoptedBy) {
    const genome = getGenome(genomeId);
    if (!genome) continue;
    nodes.push(node(genome.id, 'entity', genome.name, 'adopted'));
    triples.push(
      triple(genome.id, 'wasDerivedFrom', mutation.id, `${genome.name} adopted ${mutation.shortId}`),
    );
    pedigree.push({
      role: 'descendant',
      name: genome.name,
      accession: genome.id,
      href: accessionHref(genome.id),
      detail: 'Adopted this mutation',
    });
  }

  return finalise(
    { accession: mutation.id, name: `${mutation.shortId} ${mutation.title}`, kind: 'mutation' },
    mutation.attestations,
    nodes,
    triples,
    pedigree,
    mutation.id,
  );
}

function githubCommitUrl(genome: Genome, commit = genome.source.commit): string | null {
  const [prefix, ...rest] = genome.source.repository.split(':');
  const slug = rest.length > 0 ? rest.join(':') : prefix;
  if (prefix !== 'github' || !slug) return null;
  return `https://github.com/${slug}/commit/${commit}`;
}

export { ATTESTATION_LABEL, RELATION_GLOSS };
